### ISSUE TITLE
Mysql Backups are only 1KB

### ISSUE THREAD

**Issue by Bleala** [alaub81/backup_docker_scripts#1]
Hello there!

I tried the backup script for mysql/mariadb and the output files are only 1KB.
There are no errors during runtime, except 
```
 create Backup for Database on Container:
  * /run/secrets/mariadb_database DB on mariadb_baikal
./mariadb_backup.sh: line 58: /docker/backup/database/mariadb/mariadb_baikal-/run/secrets/mariadb_database-202111231913.sql.gz: No such file or directory
mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
ls: cannot access '/docker/backup/database/mariadb/mariadb_baikal*.gz': No such file or directory
```
But this error only happens with two different containers, there are no errors with the other containers, although i deployed them the same way, so i don't get it, why an error occurs with these two containers.

Do you have an idea what to do?

Greetings

**Comment by alaub81** [comment]
Hello @Bleala,

i have an idea. Could you please provide me some more informations on your used mariadb docker Container?

It Looks like an Environment variable is set in an other way here. There is a path in the filename… /secrets….

**Comment by Bleala** [comment]
@alaub81 
Ich werd mal in Deutsch weiterschreiben, da du laut deinem Github Profil ja Deutscher zu sein scheinst :)

Das wär der MariaDB Part in meinen Compose Files (ist immer exakt 1:1 das selbe):
(SECRETSDIR Variable wird per .env Datei gesetzt)

```
version: "3.9"

networks:                                 
  traefik_proxy:                       
    external:
      name: traefik_proxy
  gitea:
    internal: true
  default:
    driver: bridge

volumes:
  mariadb:
    name: mariadb_gitea
    driver: local

secrets:
  mariadb_database:
    file: $SECRETSDIR/mariadb_database
  mariadb_password:
    file: $SECRETSDIR/mariadb_password
  mariadb_root_password:
    file: $SECRETSDIR/mariadb_root_password
  mariadb_user:
    file: $SECRETSDIR/mariadb_user

services:
  mariadb:
    container_name: mariadb_gitea
    image: mariadb:10.6
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - gitea
    environment:
      - MARIADB_DATABASE_FILE=/run/secrets/mariadb_database
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - MARIADB_USER_FILE=/run/secrets/mariadb_user
    volumes:
      - type: bind
        source: $DOCKERDIR/mariadb/my.cnf
        target: /etc/mysql/conf.d/my.cnf
        read_only: true
      - type: volume
        source: mariadb
        target: /var/lib/mysql
        read_only: false
    secrets:
      - mariadb_database
      - mariadb_password
      - mariadb_root_password
      - mariadb_user

```

deshalb noch komischer, da die Fehlermeldung nur bei zwei Container auftritt, bei den anderen 8 nicht, da läuft es ohne Probleme durch.
Wobei nachdem die .sql.gz Dateien nur 1KB haben und wenn man sie extrahiert nichts drinnen ist, ist dann doch auch wo ein Problem^^
